//! The CredenShare API client.
//!
//! Everything sensitive happens before a request is built. By the time anything reaches the
//! network it is ciphertext plus metadata, and the content key exists only in the link this
//! client hands back to you.

use std::fmt;
use std::time::Duration;

use base64::engine::general_purpose::{STANDARD_NO_PAD, URL_SAFE_NO_PAD};
use base64::Engine as _;
use rand_core::{OsRng, RngCore};
use serde_json::{json, Map, Value};
use zeroize::Zeroizing;

use crate::crypto::{self, Field};
use crate::errors::{ApiDetails, Error, Result};

/// The production API.
pub const DEFAULT_BASE_URL: &str = "https://api.credenshare.io/v1";
/// Where recipient links live.
pub const DEFAULT_LINK_ORIGIN: &str = "https://crs.sh";

/// The only accepted encryption type. Plaintext creates are refused by the server, and this
/// client has no way to express one.
const ENCRYPTION_TYPE: &str = "e2ee-aes256-gcm";

/// The API's numeric code for an exhausted plan allowance. Distinguished from other 403s
/// because waiting does not help and the remedy is a plan change, not a retry.
const QUOTA_EXCEEDED_CODE: i64 = 61;

/// The API's numeric code for an Idempotency-Key replayed with a different body.
const IDEMPOTENCY_CONFLICT_CODE: i64 = 105;

/// The header every `POST`, `PUT` and `PATCH` carries, generated by [`CredenShare::request`]
/// when the caller has not supplied one. See [`IDEMPOTENT_METHODS`] for why `DELETE` is not on
/// that list.
const IDEMPOTENCY_HEADER: &str = "Idempotency-Key";

/// The methods that get an automatic `Idempotency-Key`, and the reason the list is not simply
/// "everything but GET".
///
/// The API consults the header on CREATES. On a `DELETE` it is not read at all, so generating
/// one buys nothing — and `DELETE /shares/{code}` shipped in 0.1.4 sending no such header, so
/// adding one now would change the bytes of an already-published surface for no gain. A caller
/// who supplies their own key on any method still has it forwarded untouched.
const IDEMPOTENT_METHODS: [&str; 3] = ["POST", "PUT", "PATCH"];

/// The most pages [`CredenShare::for_each_share`] will walk before giving up.
///
/// A bound exists because the end of the result set is not always knowable: a server that
/// omits both `total_pages` and `total` and returns full pages forever cannot be told from a
/// very large account. An unbounded walk against one hangs the caller's process and re-feeds
/// the visitor the same rows; a bounded one fails with a message naming the cause.
///
/// At the default page size of 100 this is ten million shares.
pub const MAX_PAGES: u32 = 100_000;

/// Retries for network failures. Only transport errors are retried, never an HTTP status: a
/// 5xx may have committed, and this client cannot tell. A create is safe to retry because the
/// Idempotency-Key and the body are both identical on the second attempt — which is the entire
/// reason the header is mandatory.
pub const DEFAULT_MAX_RETRIES: u32 = 2;

const CREDENTIAL_PREFIX: &str = "crs_sk_live_";

/// A parsed API credential: `crs_sk_live_<keyId>.<authSecret>[.<custodySecret>]`.
///
/// The custody secret is held here but is NEVER placed in a request. It is a separate secret
/// precisely so the server cannot reconstruct the custody private key — deriving it from the
/// auth secret, which is transmitted on every call, would mean the server *could* decrypt. Not
/// that it would; that it could.
#[derive(Clone)]
pub struct Credential {
    pub key_id: String,
    auth_secret: String,
    custody_secret: Option<String>,
}

impl Credential {
    pub fn parse(raw: &str) -> Result<Self> {
        let text = raw.trim();
        if !text.starts_with(CREDENTIAL_PREFIX) {
            return Err(Error::CredentialFormat(format!(
                "a credential starts with '{CREDENTIAL_PREFIX}'; this does not look like one"
            )));
        }
        let parts: Vec<&str> = text.split('.').collect();
        if !(2..=3).contains(&parts.len()) || parts.iter().any(|p| p.is_empty()) {
            return Err(Error::CredentialFormat(format!(
                "a credential is '{CREDENTIAL_PREFIX}<keyId>.<authSecret>' with an optional \
                 '.<custodySecret>'; this has {} part(s)",
                parts.len()
            )));
        }

        // parts[0] being non-empty only proves the PREFIX is there: "crs_sk_live_.secret"
        // splits into two non-empty parts and yields an empty key id, which then goes out in
        // an Authorization header that cannot identify anything.
        let key_id = parts[0][CREDENTIAL_PREFIX.len()..].to_string();
        if key_id.is_empty() {
            return Err(Error::CredentialFormat(
                "the credential has no key id between the prefix and the first '.'".to_string(),
            ));
        }

        Ok(Self {
            key_id,
            auth_secret: parts[1].to_string(),
            custody_secret: parts.get(2).map(|s| s.to_string()),
        })
    }

    pub fn has_custody(&self) -> bool {
        self.custody_secret.is_some()
    }

    /// The two-part value sent in the Authorization header.
    ///
    /// Assembled from the parts rather than by trimming the original string, so a third part
    /// cannot survive a formatting mistake and reach the wire.
    fn bearer(&self) -> String {
        format!("{CREDENTIAL_PREFIX}{}.{}", self.key_id, self.auth_secret)
    }

    /// The base64url custody public key to register for account custody.
    ///
    /// Only the public half leaves this machine. Any machine holding the credential derives the
    /// same keypair, so ephemeral runners need no local state.
    pub fn custody_public_key(&self) -> Result<String> {
        let secret = self.custody_secret.as_deref().ok_or_else(|| {
            Error::CredentialFormat(
                "this credential has no custody secret, so no custody keypair exists".into(),
            )
        })?;
        Ok(crypto::custody_keypair(secret)?.public_key_b64url())
    }
}

impl fmt::Debug for Credential {
    /// Never render the secrets. A credential in a log line is a credential that has to be
    /// rotated, and `#[derive(Debug)]` is how that usually happens.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<Credential {} ({})>",
            self.key_id,
            if self.has_custody() {
                "with custody"
            } else {
                "no custody"
            }
        )
    }
}

impl fmt::Display for Credential {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(self, f)
    }
}

/// A created share, and the only place its link exists.
pub struct Share {
    pub short_code: String,
    /// The full recipient link, INCLUDING the key fragment. Treat this as the secret itself:
    /// anyone holding it can read the content, and CredenShare cannot.
    pub link: String,
    /// The content key, if you need to build your own link or decrypt later.
    pub content_key: [u8; 32],
    pub expired_at: Option<String>,
    pub custody: Option<String>,
}

impl fmt::Debug for Share {
    /// The link carries the key, so it is not printed by default.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "<Share {} (link withheld)>", self.short_code)
    }
}

/// Metadata for a share. Never content, and never a key.
///
/// Deliberately thin, because the API is: `/v1` returns the short code and the expiry and
/// nothing else. There is no title here even though you supply one on create — the server does
/// not return it, and a field that is always `None` reads as broken rather than absent.
#[derive(Debug, Clone)]
pub struct ShareSummary {
    pub short_code: String,
    pub expired_at: Option<String>,
}

/// One page of shares, with the paging figures attached.
///
/// A bare `Vec` would leave a caller guessing whether more exists, and a caller who has to
/// guess guesses wrong — usually by stopping at the first short page.
#[derive(Debug, Clone)]
pub struct SharePage {
    pub shares: Vec<ShareSummary>,
    pub page: u32,
    pub limit: u32,
    pub total: Option<u32>,
    pub total_pages: Option<u32>,
}

impl SharePage {
    /// Whether another page exists.
    ///
    /// Falls back deliberately rather than answering `false` when the server omits the paging
    /// figures: reporting "no more" on a full page is what makes [`CredenShare::for_each_share`]
    /// stop after page one and return a fraction of the account as though it were all of it.
    pub fn has_more(&self) -> bool {
        page_has_more(
            self.page,
            self.limit,
            self.total,
            self.total_pages,
            self.shares.len(),
        )
    }
}

/// A share to create.
#[derive(Debug, Default)]
pub struct CreateParams {
    pub title: String,
    pub fields: Vec<Field>,
    pub description: Option<String>,
    pub passcode: Option<String>,
    pub expired_at: Option<String>,
    pub access_counts_left: Option<u32>,
    pub timed_view: Option<u32>,

    /// Generated per call unless you set it. Setting your own does NOT make a second call a
    /// no-op: encryption is randomised per call, so the body differs and the API refuses with
    /// [`Error::IdempotencyConflict`]. That is the header working, not failing. What it
    /// protects is a network retry, which this client performs itself.
    pub idempotency_key: Option<String>,

    /// Create a share under a key you already hold — a link you handed out before the create,
    /// or a fixed key in a test. It does not make the request body reproducible.
    pub content_key: Option<[u8; 32]>,
}

/// One prompt on a collect form.
///
/// `item` is the VISIBLE PROMPT — the request-side counterpart of a share field's
/// [`Field::key`], and the same trap if you reach for `label`. `field_type` decides how the
/// prompt renders for the submitter and takes the same vocabulary as a share field's type;
/// left empty it is omitted from the request, so the API applies its own default of `text`
/// rather than being handed an empty string.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RequestField {
    pub item: String,
    pub field_type: String,
}

impl RequestField {
    /// A prompt with an explicit type.
    pub fn new(item: impl Into<String>, field_type: impl Into<String>) -> Self {
        Self {
            item: item.into(),
            field_type: field_type.into(),
        }
    }

    /// A prompt rendered as one line of text, which is what most of them are.
    pub fn text(item: impl Into<String>) -> Self {
        Self::new(item, "text")
    }
}

/// A secure request to create.
///
/// [`Debug`] is hand-written and withholds [`Self::seed`]. The derived one printed it, which
/// meant a `dbg!(&params)` or a `tracing` field wrote the private key of every submission that
/// request will ever collect into a log — and unlike a credential, a leaked seed cannot be
/// rotated: rotating it would make the submissions already collected unreadable.
#[derive(Default)]
pub struct CreateRequestParams {
    pub title: String,

    /// What the person filling the link is asked for. At least one, and refused locally
    /// otherwise: a request with no fields is created successfully, returns a short code, and
    /// renders "Unable to Load Request" for whoever you send it to.
    pub fields: Vec<RequestField>,

    pub description: Option<String>,

    /// A password on the collect FORM, and the one secret in this crate that is transmitted.
    ///
    /// Unlike a share's passcode it is not mixed into any key derivation — the server decides
    /// who may see the form, so it has to be able to evaluate this. It gates access to the
    /// form and never the submissions: those are sealed to your public key, and this passcode
    /// cannot open one. Do not reuse a share passcode here.
    pub passcode: Option<String>,

    /// Defaults to **30 days** from now, applied by the API. Omitting it does not create a
    /// collect link that stays open forever.
    pub expired_at: Option<String>,

    /// How many submissions the link accepts in total.
    pub max_submission: Option<u32>,

    /// How many times the link may be opened.
    pub access_counts_left: Option<u32>,

    pub requires_login: Option<bool>,
    pub requires_mfa: Option<bool>,

    /// Email domains permitted to submit. Empty means no restriction.
    pub restricted_domain: Vec<String>,

    /// Addresses permitted to submit. Empty means no restriction.
    pub ip_whitelist: Vec<String>,

    /// Create the request under a team you belong to, rather than under yourself.
    ///
    /// Accepted only where it matches the organization the credential already acts in — the
    /// API refuses another team's id rather than silently creating the request under yours, so
    /// this selects among what the credential can already reach and never widens it.
    ///
    /// New in 0.2.0 alongside `create_request` itself, so it breaks nothing. There is
    /// deliberately no counterpart on [`CreateParams`]: that struct shipped in 0.1.4 without
    /// one, and adding a member to it would stop an exhaustive struct literal from compiling
    /// — a source break, which a minor release does not get to make. A share created under a
    /// team goes through [`CredenShare::request`] until the next major.
    pub organization_id: Option<String>,

    /// Generated per call unless you set it. Setting your own does NOT make a second call a
    /// no-op — the API refuses a replayed key carrying a different body with
    /// [`Error::IdempotencyConflict`], and a second `create_request` differs in at least its
    /// public key. What it protects is a network retry, which this client performs itself.
    pub idempotency_key: Option<String>,

    /// Derive the keypair from a seed you already hold instead of a fresh random one.
    ///
    /// The custody case: `custody_keypair(secret).seed()` gives an ephemeral runner a
    /// REPRODUCIBLE keypair, so a container that will not exist tomorrow can create a request
    /// today and its replacement can open the submissions with nothing stored anywhere. A
    /// fresh seed per request is the better default everywhere else, because it bounds what
    /// one leaked seed opens to one request.
    pub seed: Option<[u8; 32]>,
}

impl fmt::Debug for CreateRequestParams {
    /// Every field except the seed, which is rendered as its absence or its presence and
    /// never as its bytes.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CreateRequestParams")
            .field("title", &self.title)
            .field("fields", &self.fields)
            .field("description", &self.description)
            .field("passcode", &self.passcode)
            .field("expired_at", &self.expired_at)
            .field("max_submission", &self.max_submission)
            .field("access_counts_left", &self.access_counts_left)
            .field("requires_login", &self.requires_login)
            .field("requires_mfa", &self.requires_mfa)
            .field("restricted_domain", &self.restricted_domain)
            .field("ip_whitelist", &self.ip_whitelist)
            .field("organization_id", &self.organization_id)
            .field("idempotency_key", &self.idempotency_key)
            .field("seed", &self.seed.as_ref().map(|_| Withheld))
            .finish()
    }
}

/// Stands in for key material in a [`fmt::Debug`] rendering.
///
/// A unit struct rather than a string so the alternate form `{:#?}` prints
/// `seed: Some(<32 bytes withheld>)` without quotes around it, which reads as a redaction
/// rather than as a value somebody chose.
struct Withheld;

impl fmt::Debug for Withheld {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("<32 bytes withheld>")
    }
}

/// A created secure request, and the only place its seed exists.
///
/// The struct's own copy of the seed is zeroized when this value drops. That is the copy, not
/// every copy: `[u8; 32]` is `Copy`, so anything you took out with `*request.seed()` — or the
/// [`Self::access_link`] string, which carries the same 32 bytes in base64url — is yours to
/// wipe. Store one of them before this value drops; nothing else in the world holds the seed.
pub struct SecureRequest {
    pub short_code: String,

    /// The collect link to hand out. Unlike a share link it carries NO key, so it is safe to
    /// publish: holding it lets somebody SUBMIT, never read.
    pub collect_link: String,

    /// YOUR link, with the seed in the fragment. Treat it as the secret itself: anyone holding
    /// it can read every submission, and CredenShare cannot rebuild it because the seed was
    /// never ours.
    ///
    /// The whole seed in one string, which is what makes it the convenient thing to paste into
    /// a secrets manager — and the reason it is withheld from this type's [`Debug`] alongside
    /// the seed itself.
    pub access_link: String,

    /// The public half, echoed back by the API so you can confirm what was stored.
    pub public_key: String,

    pub expired_at: Option<String>,

    seed: Zeroizing<[u8; 32]>,
}

impl SecureRequest {
    /// The 32-byte seed, which is the ONLY way to read this request's submissions.
    ///
    /// It was generated on this machine and never sent — the API received the public half
    /// alone, which is what makes a submission unreadable to CredenShare and to every other
    /// submitter. Store it as you would any private key: a request whose seed is lost goes on
    /// collecting submissions that nobody, including us, can ever open.
    ///
    /// A method rather than a field so that reaching for private key material is a deliberate
    /// act that shows up in a review, as it is on [`crate::SeedKeypair`].
    pub fn seed(&self) -> &[u8; 32] {
        &self.seed
    }
}

impl fmt::Debug for SecureRequest {
    /// Never render the seed, and never the access link that carries it. A seed in a log line
    /// cannot be rotated the way a credential can: every submission already collected under it
    /// would become unreadable.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "<SecureRequest {} (seed and access link withheld)>",
            self.short_code
        )
    }
}

/// Metadata for a secure request. Never a submission, and never a seed.
#[derive(Debug, Clone)]
pub struct RequestSummary {
    pub short_code: String,
    pub expired_at: Option<String>,

    /// The public half supplied on create, returned so you can confirm what was stored.
    ///
    /// `None` for a legacy request created without one — a request whose submissions cannot be
    /// sealed to anybody — and also for one of your own that has expired, which the API
    /// reports as a bare short code rather than as a 404.
    pub public_key: Option<String>,
}

/// One page of secure requests, with the paging figures attached.
#[derive(Debug, Clone)]
pub struct RequestPage {
    pub requests: Vec<RequestSummary>,
    pub page: u32,
    pub limit: u32,
    pub total: Option<u32>,
    pub total_pages: Option<u32>,
}

impl RequestPage {
    /// Whether another page exists.
    ///
    /// Answered exactly as [`SharePage::has_more`] answers it, fallback included, because the
    /// two lists are paginated identically and a divergence between them would be silent.
    pub fn has_more(&self) -> bool {
        page_has_more(
            self.page,
            self.limit,
            self.total,
            self.total_pages,
            self.requests.len(),
        )
    }
}

/// What a [`CredenShare::delete_request`] call did.
///
/// The endpoint is two-step by design, so `outcome` answers a question the caller cannot work
/// out locally. It is a string rather than an enum for the same reason [`Share::custody`] is
/// one: a value this version has not heard of must not become an error on the path whose whole
/// job is reporting what happened.
#[derive(Debug, Clone)]
pub struct RequestDeletion {
    pub short_code: String,

    /// `"expired"` — it was active, new submissions have stopped, and the ones already
    /// received are preserved — or `"deleted"`, meaning it was already expired and is now
    /// gone.
    pub outcome: Option<String>,
}

/// One sealed submission: the blob, not its contents.
///
/// Exactly the four members the handler emits — `short_code`, `created_at`, `data` and
/// `encryption_type` — and no `expired_at`. A submission has no expiry of its own: the REQUEST
/// expires, and expiring it stops new submissions rather than dating the ones already
/// collected. A member the API never populates reads as a broken field rather than an absent
/// one, so there is none, here as in the Node, Python and Go clients.
#[derive(Debug, Clone)]
pub struct Submission {
    pub short_code: String,
    pub created_at: Option<String>,

    /// The sealed submission, **padded standard base64** — not the unpadded base64url the
    /// request's public key travelled as. Pass it to [`Self::decrypt`] verbatim.
    pub data: String,

    pub encryption_type: Option<String>,
}

impl Submission {
    /// Open this submission with the seed kept when the request was created.
    ///
    /// Sealed blobs are handed back and opened on request rather than decrypted on arrival,
    /// for the same reason [`crate::decrypt_content`] is a separate call from
    /// [`CredenShare::list_shares`]: the seed belongs to the caller, and a list that decrypted
    /// silently would demand it on every read — including the reads that only want to know how
    /// many arrived.
    pub fn decrypt(&self, seed: &[u8]) -> Result<Vec<Field>> {
        crypto::decrypt_submission(&self.data, seed)
    }
}

/// Every submission to one request, in the one response the API answers with.
///
/// Not paginated, and carrying no paging figures for that reason: the endpoint returns the
/// whole set and reads neither `page` nor `limit`. `openapi.yaml` agrees — it documents no
/// `pagination` block on this response, and an earlier revision that did has been corrected.
/// Members read from figures that never arrive are how a walk asks for a page two that does
/// not exist and is handed page one again; a member that is always absent reads as a broken
/// field rather than an absent one, so there is none.
#[derive(Debug, Clone)]
pub struct SubmissionPage {
    pub submissions: Vec<Submission>,

    /// How many rows the API reports in this response, where it reports a count.
    ///
    /// The API's own figure, alongside the rows rather than instead of them: it counts what
    /// the response contains, so a mismatch with `submissions.len()` is worth investigating
    /// rather than papering over.
    pub count: Option<u32>,

    /// How many submissions the API WITHHELD because they are not end-to-end encrypted.
    ///
    /// A request created before client-side encryption, or without a public key, collects
    /// submissions the server can read — and it refuses to hand those to a credential rather
    /// than make this the one endpoint where a bearer token yields readable secrets. They are
    /// counted rather than silently dropped, so a reconciliation against your dashboard does
    /// not report submissions as missing when they are merely unreadable this way.
    ///
    /// Every request this crate creates carries a public key, so its own requests never
    /// produce one.
    pub skipped_not_end_to_end_encrypted: Option<u32>,
}

/// Usage figures for the account — or for the TEAM, when the credential acts in one.
///
/// The per-member breakdown the dashboard shows is deliberately absent from the API: a
/// credential scoped to read statistics should not become a way to enumerate colleagues.
#[derive(Debug, Clone)]
pub struct Stats {
    pub shares: ShareCounts,

    /// Views per day, oldest first and zero-filled, so a quiet day is a zero rather than a
    /// missing row. Always present, and possibly empty.
    pub daily_views: Vec<DailyView>,
}

/// Share counts.
///
/// Named for what it holds rather than for the call that returns it, so `stats.shares.active`
/// reads the same here as it does in the Node, Python and Go clients.
#[derive(Debug, Clone, Default)]
pub struct ShareCounts {
    pub active: u32,
    pub expired: u32,
    pub total_viewed: u32,
}

/// One day's views.
#[derive(Debug, Clone)]
pub struct DailyView {
    pub date: String,
    pub count: u32,
}

/// Client configuration. `ClientOptions::default()` targets production.
#[derive(Debug, Clone)]
pub struct ClientOptions {
    pub base_url: String,
    pub link_origin: String,
    pub timeout: Duration,
    pub max_retries: u32,
}

impl Default for ClientOptions {
    fn default() -> Self {
        Self {
            base_url: DEFAULT_BASE_URL.to_string(),
            link_origin: DEFAULT_LINK_ORIGIN.to_string(),
            timeout: Duration::from_secs(30),
            max_retries: DEFAULT_MAX_RETRIES,
        }
    }
}

/// The API client.
#[derive(Debug)]
pub struct CredenShare {
    pub credential: Credential,
    options: ClientOptions,
    agent: ureq::Agent,
}

impl CredenShare {
    /// Build a client from a credential, against production.
    pub fn new(credential: &str) -> Result<Self> {
        Self::with_options(credential, ClientOptions::default())
    }

    pub fn with_options(credential: &str, mut options: ClientOptions) -> Result<Self> {
        options.base_url = options.base_url.trim_end_matches('/').to_string();
        options.link_origin = options.link_origin.trim_end_matches('/').to_string();

        let agent = ureq::AgentBuilder::new()
            .timeout(options.timeout)
            .user_agent(&format!("credenshare-rust/{}", crate::VERSION))
            .build();

        Ok(Self {
            credential: Credential::parse(credential)?,
            options,
            agent,
        })
    }

    /// Assemble a recipient link.
    ///
    /// The key lives in the fragment, which browsers never send to a server. That is what makes
    /// the link readable by its holder and opaque to us.
    pub fn link_for(&self, short_code: &str, content_key: &[u8]) -> Result<String> {
        Ok(format!(
            "{}/{short_code}#{}",
            self.options.link_origin,
            crypto::encode_fragment(content_key)?
        ))
    }

    /// Not implemented, on purpose.
    ///
    /// The recipient path is deliberately absent from the API, because bearer auth skips the
    /// proof-of-work and captcha gates that protect it, and exposing it to a credential would
    /// be an enumeration bypass. Open the link in a browser, or use
    /// [`crate::decrypt_content`] on a blob you already hold.
    pub fn read_link(&self, _link: &str) -> Result<Vec<Field>> {
        Err(Error::Internal(
            "the recipient read path is not exposed over the API by design; open the link in a \
             browser, or use decrypt_content on a blob you already have",
        ))
    }

    /// Encrypt `fields` locally and create a share.
    pub fn create_share(&self, params: CreateParams) -> Result<Share> {
        let content_key = params.content_key.unwrap_or_else(crypto::new_content_key);
        let blob =
            crypto::encrypt_content(&content_key, &params.fields, params.passcode.as_deref())?;

        let mut body = Map::new();
        body.insert("title".into(), json!(params.title));
        body.insert("encryption_type".into(), json!(ENCRYPTION_TYPE));
        body.insert("data".into(), json!(blob));
        body.insert(
            "access_token".into(),
            json!(crypto::access_token(&content_key)?),
        );

        if let Some(description) = &params.description {
            body.insert("description".into(), json!(description));
        }
        if let Some(passcode) = &params.passcode {
            body.insert(
                "passcode_verifier".into(),
                json!(crypto::passcode_verifier(passcode)?),
            );
        }
        if let Some(expired_at) = &params.expired_at {
            body.insert("expired_at".into(), json!(expired_at));
        }
        if let Some(count) = params.access_counts_left {
            body.insert("access_counts_left".into(), json!(count));
        }
        if let Some(seconds) = params.timed_view {
            body.insert("timed_view".into(), json!(seconds));
        }

        // Required by the API, not optional. A retried automation must not create a second copy
        // of a credential in the world, with its own link and audit trail, that the caller does
        // not know exists.
        let idempotency_key = params.idempotency_key.unwrap_or_else(random_token);

        let data = self.request(
            "POST",
            "/shares",
            Some(Value::Object(body)),
            &[],
            &[(IDEMPOTENCY_HEADER, idempotency_key.as_str())],
        )?;

        let short_code = data
            .get("short_code")
            .and_then(Value::as_str)
            .ok_or(Error::Internal("the API returned no short_code"))?
            .to_string();

        Ok(Share {
            link: self.link_for(&short_code, &content_key)?,
            short_code,
            content_key,
            expired_at: data
                .get("expired_at")
                .and_then(Value::as_str)
                .map(str::to_string),
            custody: data
                .get("custody")
                .and_then(Value::as_str)
                .map(str::to_string),
        })
    }

    /// One page of the account's shares, newest first. Metadata only.
    pub fn list_shares(&self, limit: u32, page: u32) -> Result<SharePage> {
        let limit = if limit == 0 { 25 } else { limit };
        let page = if page == 0 { 1 } else { page };
        let data = self.request(
            "GET",
            "/shares",
            None,
            &[("limit", limit.to_string()), ("page", page.to_string())],
            &[],
        )?;

        // A row this client cannot read is an error, not an omission. Dropping it silently
        // while `total` still reports the true count produces a list that is quietly short,
        // and a reconciliation against it reports shares as missing that are not.
        let shares: Vec<ShareSummary> = match data.get("shares").and_then(Value::as_array) {
            None => Vec::new(),
            Some(rows) => rows
                .iter()
                .map(|row| {
                    let short_code =
                        row.get("short_code")
                            .and_then(Value::as_str)
                            .ok_or_else(|| {
                                Error::InternalOwned(
                                    "a share row carried no string short_code; refusing to \
                                     return a list that is silently short"
                                        .to_string(),
                                )
                            })?;
                    Ok(ShareSummary {
                        short_code: short_code.to_string(),
                        expired_at: row
                            .get("expired_at")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                    })
                })
                .collect::<Result<Vec<_>>>()?,
        };

        let pagination = data.get("pagination");
        let read = |name: &str| {
            pagination
                .and_then(|p| p.get(name))
                .and_then(Value::as_u64)
                .map(|v| v as u32)
        };

        Ok(SharePage {
            shares,
            page: read("page").unwrap_or(page),
            limit: read("limit").unwrap_or(limit),
            total: read("total"),
            total_pages: read("total_pages"),
        })
    }

    /// Every share, page by page, handed to `visit`.
    ///
    /// Written here because the hand-rolled version is usually wrong in the same way: it stops
    /// on the first page shorter than `limit`, which is a page the server is entitled to return
    /// in the middle of a result set.
    /// # Errors
    ///
    /// Beyond anything [`Self::list_shares`] can return, the walk itself refuses two things
    /// rather than looping:
    ///
    /// - the API echoing a page number other than the one requested, which makes progress
    ///   unobservable;
    /// - reaching [`MAX_PAGES`] without the API ever signalling the end of the result set.
    ///
    /// Both are [`Error::Internal`] / [`Error::InternalOwned`] and both are preferable to the
    /// alternative, which is a process that never returns.
    pub fn for_each_share<F>(&self, limit: u32, mut visit: F) -> Result<()>
    where
        F: FnMut(&ShareSummary) -> Result<()>,
    {
        let limit = if limit == 0 { 100 } else { limit };
        let mut page = 1u32;
        loop {
            let batch = self.list_shares(limit, page)?;

            // A server that echoes a constant page number makes progress unobservable, and
            // has_more's last-resort fallback (a full page probably has a successor) would
            // then loop forever on the same rows. Terminate loudly instead of hanging.
            if batch.page != page {
                return Err(Error::Internal(
                    "the API echoed a different page number than the one requested, so paging \
                     cannot be trusted to terminate",
                ));
            }

            for share in &batch.shares {
                visit(share)?;
            }
            if !batch.has_more() {
                return Ok(());
            }
            if page >= MAX_PAGES {
                return Err(Error::InternalOwned(format!(
                    "stopped after {MAX_PAGES} pages without the API signalling the end of the \
                     result set; it sent neither total_pages nor total, and every page came \
                     back full"
                )));
            }
            page += 1;
        }
    }

    /// One share's metadata.
    ///
    /// Does not consume a view, evaluate a passcode, or return content. A share belonging to
    /// another account reports exactly as one that does not exist.
    pub fn get_share(&self, short_code: &str) -> Result<ShareSummary> {
        check_short_code(short_code)?;
        let data = self.request("GET", &format!("/shares/{short_code}"), None, &[], &[])?;
        Ok(ShareSummary {
            short_code: data
                .get("short_code")
                .and_then(Value::as_str)
                .unwrap_or(short_code)
                .to_string(),
            expired_at: data
                .get("expired_at")
                .and_then(Value::as_str)
                .map(str::to_string),
        })
    }

    /// Expire a share immediately.
    ///
    /// Irreversible: afterwards the content is unrecoverable by anyone, including CredenShare —
    /// the key was never ours, and now the ciphertext is gone too.
    ///
    /// The share is REMOVED, not flagged. A later [`Self::get_share`] returns
    /// [`Error::NotFound`] rather than a row with an expiry set, and it drops out of
    /// [`Self::list_shares`]. Worth knowing if you reconcile against your own records: a share
    /// you expired and one that never existed look identical afterwards.
    pub fn expire_share(&self, short_code: &str) -> Result<()> {
        check_short_code(short_code)?;
        self.request("DELETE", &format!("/shares/{short_code}"), None, &[], &[])?;
        Ok(())
    }

    /// Assemble a collect link for a request's short code.
    ///
    /// `{link_origin}/r/{short_code}`, which is the path the app serves the collect form on.
    /// Unlike [`Self::link_for`] there is no fragment, because there is no key to put in one:
    /// this link is safe to publish, and holding it lets somebody submit rather than read.
    pub fn collect_link_for(&self, short_code: &str) -> String {
        format!("{}/r/{short_code}", self.options.link_origin)
    }

    /// Assemble YOUR access link for a request: the seed in the fragment.
    ///
    /// The other half of [`Self::collect_link_for`], and the opposite in every way that
    /// matters — treat the result as the secret itself, because it IS the ability to read
    /// every submission, on any device, with nothing stored. Browsers never send a fragment to
    /// a server, so the seed stays yours; CredenShare cannot rebuild this link, because the
    /// seed was never ours.
    ///
    /// The point of it is turning a seed you stored at create time back into something a
    /// person can open, which is also why hand-assembly is the wrong move: the fragment is
    /// version-prefixed (`"1" + base64url(seed)`) and a hand-built one without the prefix
    /// fails as a damaged link.
    ///
    /// A wrong-length seed is [`Error::MalformedKey`] here rather than an error from inside a
    /// crypto primitive, so the message names the argument the caller passed.
    pub fn access_link_for(&self, short_code: &str, seed: &[u8]) -> Result<String> {
        if seed.len() != crypto::SEED_LENGTH {
            return Err(Error::MalformedKey(format!(
                "a request seed is {} bytes; this one is {}",
                crypto::SEED_LENGTH,
                seed.len()
            )));
        }
        Ok(format!(
            "{}/r/{short_code}#{}",
            self.options.link_origin,
            crypto::encode_fragment(seed)?
        ))
    }

    /// Mint a keypair, create a secure request, and hand you the seed.
    ///
    /// The keypair is generated HERE. The API receives the public half; the 32-byte seed exists
    /// only in the returned [`SecureRequest`] and is never transmitted — which is the whole
    /// point of the endpoint rather than a detail of it. Submissions are sealed to the public
    /// key, so that seed is the only thing in the world able to read them.
    ///
    /// Store it before the returned value drops. A request whose seed is lost goes on
    /// collecting submissions that nobody, CredenShare included, can ever open — and there is
    /// no recovery path, by construction.
    ///
    /// Pass [`CreateRequestParams::seed`] to derive the keypair from a seed you already hold,
    /// which is what a runner deriving from its credential's custody secret wants.
    pub fn create_request(&self, params: CreateRequestParams) -> Result<SecureRequest> {
        check_request_fields(&params.fields)?;

        let seed = params.seed.unwrap_or_else(crypto::new_seed);
        let keypair = crypto::keypair_from_seed(&seed)?;

        let mut body = Map::new();
        body.insert("title".into(), json!(params.title));
        // UNPADDED base64url, which is the encoding the API's key validator accepts. The
        // submission blobs that come back later are padded STANDARD base64: the same feature,
        // two encodings, and feeding either decoder the other's output fails.
        body.insert("public_key".into(), json!(keypair.public_key_b64url()));
        body.insert(
            "fields".into(),
            Value::Array(
                params
                    .fields
                    .iter()
                    .map(|field| {
                        let mut prompt = Map::new();
                        prompt.insert("item".into(), json!(field.item));
                        // Omitted rather than sent empty, so the API's own default of `text`
                        // applies instead of a field with no renderer.
                        if !field.field_type.is_empty() {
                            prompt.insert("type".into(), json!(field.field_type));
                        }
                        Value::Object(prompt)
                    })
                    .collect(),
            ),
        );

        if let Some(description) = &params.description {
            body.insert("description".into(), json!(description));
        }
        if let Some(passcode) = &params.passcode {
            // Sent, unlike a share's. See CreateRequestParams::passcode: the server evaluates
            // this one to gate the form, and it opens nothing.
            body.insert("passcode".into(), json!(passcode));
        }
        if let Some(expired_at) = &params.expired_at {
            body.insert("expired_at".into(), json!(expired_at));
        }
        if let Some(count) = params.max_submission {
            body.insert("max_submission".into(), json!(count));
        }
        if let Some(count) = params.access_counts_left {
            body.insert("access_counts_left".into(), json!(count));
        }
        if let Some(flag) = params.requires_login {
            body.insert("requires_login".into(), json!(flag));
        }
        if let Some(flag) = params.requires_mfa {
            body.insert("requires_mfa".into(), json!(flag));
        }
        if !params.restricted_domain.is_empty() {
            body.insert("restricted_domain".into(), json!(params.restricted_domain));
        }
        if !params.ip_whitelist.is_empty() {
            body.insert("ip_whitelist".into(), json!(params.ip_whitelist));
        }
        if let Some(organization_id) = &params.organization_id {
            body.insert("organization_id".into(), json!(organization_id));
        }

        // Required by the API, as it is on a share, and for a sharper reason: a duplicate
        // collect link is not inert — a person can fill it in, and the submission lands
        // somewhere its owner never looks.
        let idempotency_key = params.idempotency_key.unwrap_or_else(random_token);

        // Belt and braces at the boundary, in the manner of the custody assertion in
        // [`Self::request`]. Asserted against the SERIALIZED body rather than against the
        // field list above, so a seed that arrived through a title, a description or a prompt
        // is caught too — and against the outgoing Idempotency-Key, because a caller deriving
        // a deterministic key from a deterministic seed has the seed in hand and that header
        // travels on the same request as the body.
        let body = Value::Object(body);
        let outgoing = format!("{body}{idempotency_key}");
        if seed_renderings(&seed)
            .iter()
            .any(|rendering| outgoing.contains(rendering.as_str()))
        {
            return Err(Error::RequestSeedTransmitted);
        }

        let data = self.request(
            "POST",
            "/requests",
            Some(body),
            &[],
            &[(IDEMPOTENCY_HEADER, idempotency_key.as_str())],
        )?;

        let short_code = data
            .get("short_code")
            .and_then(Value::as_str)
            .ok_or(Error::Internal("the API returned no short_code"))?
            .to_string();

        Ok(SecureRequest {
            collect_link: self.collect_link_for(&short_code),
            access_link: self.access_link_for(&short_code, &seed)?,
            short_code,
            // Echoed back by the API, and falling back to what was sent rather than to an
            // empty string: a caller comparing the two is checking exactly this.
            public_key: data
                .get("public_key")
                .and_then(Value::as_str)
                .map(str::to_string)
                .unwrap_or_else(|| keypair.public_key_b64url()),
            expired_at: data
                .get("expired_at")
                .and_then(Value::as_str)
                .map(str::to_string),
            seed: Zeroizing::new(seed),
        })
    }

    /// One page of the account's secure requests, newest first. Metadata only.
    pub fn list_requests(&self, limit: u32, page: u32) -> Result<RequestPage> {
        // 25, which is the API's default for every v1 list — the share list's figure, not a
        // different one. The handler reads one constant for all of them, so asking for 10
        // would make every paging figure in the response disagree with the dashboard's.
        // (openapi.yaml documents no limit parameter at all; an earlier revision implied 10
        // for this endpoint, and the deployed default is what this follows.)
        let limit = if limit == 0 { 25 } else { limit };
        let page = if page == 0 { 1 } else { page };
        let data = self.request(
            "GET",
            "/requests",
            None,
            &[("limit", limit.to_string()), ("page", page.to_string())],
            &[],
        )?;

        // A row this client cannot read is an error, not an omission — the same rule
        // [`Self::list_shares`] follows, for the same reason: a quietly short list makes a
        // reconciliation report requests as missing that are not.
        let requests: Vec<RequestSummary> = match data.get("requests").and_then(Value::as_array) {
            None => Vec::new(),
            Some(rows) => rows
                .iter()
                .map(|row| {
                    let short_code =
                        row.get("short_code")
                            .and_then(Value::as_str)
                            .ok_or_else(|| {
                                Error::InternalOwned(
                                    "a request row carried no string short_code; refusing to \
                                     return a list that is silently short"
                                        .to_string(),
                                )
                            })?;
                    Ok(RequestSummary {
                        short_code: short_code.to_string(),
                        expired_at: row
                            .get("expired_at")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                        public_key: row
                            .get("public_key")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                    })
                })
                .collect::<Result<Vec<_>>>()?,
        };

        let pagination = data.get("pagination");
        let read = |name: &str| {
            pagination
                .and_then(|p| p.get(name))
                .and_then(Value::as_u64)
                .map(|v| v as u32)
        };

        Ok(RequestPage {
            requests,
            page: read("page").unwrap_or(page),
            limit: read("limit").unwrap_or(limit),
            total: read("total"),
            total_pages: read("total_pages"),
        })
    }

    /// Every secure request, page by page, handed to `visit`.
    ///
    /// The same walk as [`Self::for_each_share`], with the same two refusals rather than a
    /// loop: an echoed page number that is not the one requested, and [`MAX_PAGES`] reached
    /// without the API ever signalling the end.
    pub fn for_each_request<F>(&self, limit: u32, mut visit: F) -> Result<()>
    where
        F: FnMut(&RequestSummary) -> Result<()>,
    {
        let limit = if limit == 0 { 100 } else { limit };
        let mut page = 1u32;
        loop {
            let batch = self.list_requests(limit, page)?;

            if batch.page != page {
                return Err(Error::Internal(
                    "the API echoed a different page number than the one requested, so paging \
                     cannot be trusted to terminate",
                ));
            }

            for request in &batch.requests {
                visit(request)?;
            }
            if !batch.has_more() {
                return Ok(());
            }
            if page >= MAX_PAGES {
                return Err(Error::InternalOwned(format!(
                    "stopped after {MAX_PAGES} pages without the API signalling the end of the \
                     result set; it sent neither total_pages nor total, and every page came \
                     back full"
                )));
            }
            page += 1;
        }
    }

    /// One request's metadata.
    ///
    /// A request belonging to another account reports exactly as one that does not exist. One
    /// of YOUR OWN that has expired reports as a bare short code — `expired_at` and
    /// `public_key` both absent — rather than as [`Error::NotFound`], so a summary with
    /// nothing on it means expired rather than missing.
    pub fn get_request(&self, short_code: &str) -> Result<RequestSummary> {
        check_short_code(short_code)?;
        let data = self.request("GET", &format!("/requests/{short_code}"), None, &[], &[])?;
        Ok(RequestSummary {
            short_code: data
                .get("short_code")
                .and_then(Value::as_str)
                .unwrap_or(short_code)
                .to_string(),
            expired_at: data
                .get("expired_at")
                .and_then(Value::as_str)
                .map(str::to_string),
            public_key: data
                .get("public_key")
                .and_then(Value::as_str)
                .map(str::to_string),
        })
    }

    /// Expire a secure request — or delete an already-expired one.
    ///
    /// Two calls, two effects. The first EXPIRES an active request, which stops new
    /// submissions while preserving the ones already received; a second call on an
    /// already-expired request removes it outright, submissions included.
    /// [`RequestDeletion::outcome`] says which happened, so read it rather than assuming the
    /// first — the effect depends on state the caller may not hold, which is also why this is
    /// named after the operation rather than after its effect like [`Self::expire_share`].
    ///
    /// A retry is the one hazard here, and no header protects against it: the API does not
    /// deduplicate deletes, which is why this call sends no `Idempotency-Key` — one would be
    /// read by nothing. A retried call the server DID receive therefore performs the second
    /// step. This client retries only transport failures, and `outcome` is how you find out.
    pub fn delete_request(&self, short_code: &str) -> Result<RequestDeletion> {
        check_short_code(short_code)?;
        let data = self.request("DELETE", &format!("/requests/{short_code}"), None, &[], &[])?;
        Ok(RequestDeletion {
            short_code: data
                .get("short_code")
                .and_then(Value::as_str)
                .unwrap_or(short_code)
                .to_string(),
            outcome: data
                .get("outcome")
                .and_then(Value::as_str)
                .map(str::to_string),
        })
    }

    /// Every submission to one request, sealed, in one call.
    ///
    /// The only read on the API that returns content, and not a hole in the metadata-only rule
    /// so much as the point of it: every `data` blob is sealed to the request's public key, so
    /// what arrives is something CredenShare cannot open, handed to the one party who can.
    /// Open a blob with [`Submission::decrypt`] and the seed from [`Self::create_request`].
    ///
    /// No `limit` and no `page`, because the endpoint has neither: it answers with the whole
    /// set and reads neither parameter. Taking them would have been a signature that lies —
    /// the caller passes 10, receives 400 rows, and then pages forever through a result set
    /// that arrived complete on the first call.
    ///
    /// Check [`SubmissionPage::skipped_not_end_to_end_encrypted`] when reconciling counts: the
    /// API withholds submissions it could read itself, and says how many.
    pub fn list_submissions(&self, short_code: &str) -> Result<SubmissionPage> {
        check_short_code(short_code)?;
        let data = self.request(
            "GET",
            &format!("/requests/{short_code}/submissions"),
            None,
            &[],
            &[],
        )?;

        let submissions: Vec<Submission> = match data.get("submissions").and_then(Value::as_array) {
            None => Vec::new(),
            Some(rows) => rows
                .iter()
                .map(|row| {
                    let short_code =
                        row.get("short_code")
                            .and_then(Value::as_str)
                            .ok_or_else(|| {
                                Error::InternalOwned(
                                    "a submission row carried no string short_code; refusing to \
                                     return a list that is silently short"
                                        .to_string(),
                                )
                            })?;
                    // Refused rather than defaulted to an empty string. A submission with no
                    // blob is one that cannot be opened, and returning it as though it were
                    // readable moves the failure to whoever calls decrypt.
                    let blob = row.get("data").and_then(Value::as_str).ok_or_else(|| {
                        Error::InternalOwned(format!(
                            "submission {short_code} carried no string data; refusing to \
                             return a submission whose blob is silently empty"
                        ))
                    })?;
                    Ok(Submission {
                        short_code: short_code.to_string(),
                        created_at: row
                            .get("created_at")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                        data: blob.to_string(),
                        encryption_type: row
                            .get("encryption_type")
                            .and_then(Value::as_str)
                            .map(str::to_string),
                    })
                })
                .collect::<Result<Vec<_>>>()?,
        };

        let top = |name: &str| data.get(name).and_then(Value::as_u64).map(|v| v as u32);

        Ok(SubmissionPage {
            submissions,
            count: top("count"),
            skipped_not_end_to_end_encrypted: top("skipped_not_end_to_end_encrypted"),
        })
    }

    /// Every submission to one request, handed to `visit` still sealed.
    ///
    /// ONE call, and then it stops. There is no walk here and no page bound, because the
    /// endpoint is not paginated: it answers with the whole set. Kept as a method rather than
    /// left to the caller so that the request surface has the same shape as
    /// [`Self::for_each_share`] and [`Self::for_each_request`], and so that a future
    /// paginated version of this endpoint is handled in one function rather than in every
    /// caller's loop.
    pub fn for_each_submission<F>(&self, short_code: &str, mut visit: F) -> Result<()>
    where
        F: FnMut(&Submission) -> Result<()>,
    {
        for submission in &self.list_submissions(short_code)?.submissions {
            visit(submission)?;
        }
        Ok(())
    }

    /// The account's usage figures — or the team's, when this credential acts in one.
    pub fn get_stats(&self) -> Result<Stats> {
        let data = self.request("GET", "/stats", None, &[], &[])?;

        // Required rather than defaulted. A response with no share figures at all is not an
        // account with none, and reporting zeros for it would read as an empty account.
        let shares = data
            .get("shares")
            .ok_or(Error::Internal("the API returned no share figures"))?;
        // Inside the object the three counts default to zero, because they are always sent and
        // a member a future API drops is better read as absent than as a hard failure here.
        let count = |name: &str| {
            shares
                .get(name)
                .and_then(Value::as_u64)
                .map(|v| v as u32)
                .unwrap_or(0)
        };

        let daily_views: Vec<DailyView> = match data.get("daily_views").and_then(Value::as_array) {
            None => Vec::new(),
            Some(rows) => rows
                .iter()
                .map(|row| {
                    // The series is zero-filled, so both members are always present. A row
                    // missing either is refused rather than read as a quiet day: a silently
                    // zeroed bucket in a chart is indistinguishable from a real one.
                    let date = row.get("date").and_then(Value::as_str).ok_or_else(|| {
                        Error::InternalOwned(
                            "a daily_views row carried no string date; refusing to return a \
                             series with a silently zeroed day"
                                .to_string(),
                        )
                    })?;
                    let views = row.get("count").and_then(Value::as_u64).ok_or_else(|| {
                        Error::InternalOwned(format!(
                            "the daily_views row for {date} carried no numeric count; refusing \
                             to return a series with a silently zeroed day"
                        ))
                    })?;
                    Ok(DailyView {
                        date: date.to_string(),
                        count: views as u32,
                    })
                })
                .collect::<Result<Vec<_>>>()?,
        };

        Ok(Stats {
            shares: ShareCounts {
                active: count("active"),
                expired: count("expired"),
                total_viewed: count("total_viewed"),
            },
            daily_views,
        })
    }

    /// Call an endpoint directly, including one this crate does not model.
    ///
    /// The escape hatch, and the same code path every method above goes through: `query` is
    /// `&[("limit", "10".to_string())]`, `headers` is `&[("X-Thing", "value")]`, `path` starts
    /// with `/` and is appended to the configured base URL, and the return value is the parsed
    /// JSON body. Errors map to the same variants and a transport failure is retried the same
    /// way.
    ///
    /// # The Idempotency-Key
    ///
    /// A `POST`, `PUT` or `PATCH` carries one. If `headers` already has an `Idempotency-Key` it
    /// is left exactly as supplied — a caller reproducing a key across process restarts is
    /// doing the thing the header is for, and overwriting it would break precisely that.
    /// Otherwise one is generated here, so a write through this method cannot leave a second
    /// object behind on a retry just because it was made through the generic path rather than a
    /// typed one.
    ///
    /// The generated key is computed ONCE and reused across this call's own retries. A key that
    /// changed per attempt would make every retry a fresh request as far as the API is
    /// concerned, which is the failure the header exists to prevent.
    ///
    /// Every OTHER method gets none, including `DELETE`. A `GET` is not a write, and minting a
    /// key for every read would fill the API's 24-hour idempotency store with values nothing
    /// will ever replay; a `DELETE` is a write, but the API does not consult the header on one,
    /// so a generated key would be inert — and `DELETE /shares/{code}` shipped in 0.1.4 sending
    /// none, which is a wire detail a minor release does not get to change. Supply your own on
    /// any method and it is forwarded regardless.
    pub fn request(
        &self,
        method: &str,
        path: &str,
        body: Option<Value>,
        query: &[(&str, String)],
        headers: &[(&str, &str)],
    ) -> Result<Value> {
        // A path without the leading slash silently produces something like
        // `https://api.credenshare.io/v1shares`, which is a 404 that reads as a missing
        // endpoint rather than as a typo.
        if !path.starts_with('/') {
            return Err(Error::InvalidArgument(format!(
                "a path starts with '/' and is appended to the base URL; '{path}' would \
                 produce '{}{path}'",
                self.options.base_url
            )));
        }

        let authorization = format!("Bearer {}", self.credential.bearer());
        // Belt and braces. `bearer` is assembled from parts so a custody secret cannot reach
        // the header, but this asserts the property at the boundary rather than trusting a
        // constructor elsewhere in the file.
        if let Some(custody) = &self.credential.custody_secret {
            if authorization.contains(custody.as_str()) {
                return Err(Error::CustodySecretTransmitted);
            }
        }

        // Allow-listed rather than "not a GET". See IDEMPOTENT_METHODS: the difference is
        // DELETE, where a generated key is inert at the API and would change bytes 0.1.4
        // already published.
        let needs_idempotency_key = IDEMPOTENT_METHODS
            .iter()
            .any(|candidate| method.eq_ignore_ascii_case(candidate))
            && !headers
                .iter()
                .any(|(key, _)| key.eq_ignore_ascii_case(IDEMPOTENCY_HEADER));
        let generated_key = if needs_idempotency_key {
            random_token()
        } else {
            String::new()
        };
        let mut sent: Vec<(&str, &str)> = headers.to_vec();
        if needs_idempotency_key {
            sent.push((IDEMPOTENCY_HEADER, generated_key.as_str()));
        }

        let url = format!("{}{path}", self.options.base_url);
        let mut attempt = 0u32;

        loop {
            let mut request = self
                .agent
                .request(method, &url)
                .set("Authorization", &authorization);
            for (key, value) in query {
                request = request.query(key, value);
            }
            for (key, value) in &sent {
                request = request.set(key, value);
            }

            let outcome = match &body {
                Some(value) => request.send_json(value.clone()),
                None => request.call(),
            };

            match outcome {
                Ok(response) => return parse_success(response),
                Err(ureq::Error::Status(status, response)) => {
                    return Err(error_for(status, response))
                }
                Err(transport) => {
                    // Retry only the failures that prove nothing was received. A 5xx might have
                    // committed and this client cannot tell, so it is surfaced above rather
                    // than repeated.
                    if attempt >= self.options.max_retries {
                        return Err(Error::Transport(format!(
                            "could not reach the API after {} attempt(s): {transport}",
                            attempt + 1
                        )));
                    }
                    // Plain exponential backoff, no jitter: the retry count is 2 by default, so
                    // a thundering herd is not the failure mode worth complicating this for.
                    std::thread::sleep(Duration::from_millis(500 * (1 << attempt)));
                    attempt += 1;
                }
            }
        }
    }
}

/// Reject a short code that could change which endpoint the request reaches.
///
/// The code is interpolated into the request path. Without this, a value containing `/`, `?`
/// or `#` escapes `/shares/` entirely and retargets an authenticated request — including at
/// endpoints this SDK never exposes.
fn check_short_code(code: &str) -> Result<()> {
    if code.is_empty() || code.len() > 64 {
        return Err(Error::InvalidArgument(format!(
            "a short code is 1-64 characters; this one is {}",
            code.len()
        )));
    }
    if !code
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
    {
        return Err(Error::InvalidArgument(
            "a short code is alphanumeric with - and _; this one would change the request path"
                .to_string(),
        ));
    }
    Ok(())
}

/// Reject a field array that would create a collect link nobody can usefully fill in.
///
/// The API requires at least one field. A request created without them succeeds, returns a
/// short code, and renders "Unable to Load Request" for whoever it was sent to — the same class
/// of silent failure as a share field with no label, refused here for the same reason. An empty
/// `item` is the other half of it: the prompt renders blank, and nothing errors anywhere.
fn check_request_fields(fields: &[RequestField]) -> Result<()> {
    if fields.is_empty() {
        return Err(Error::InvalidArgument(
            "a secure request needs at least one field; one created without any returns a short \
             code and then renders 'Unable to Load Request' for whoever you send it to"
                .to_string(),
        ));
    }
    for (index, field) in fields.iter().enumerate() {
        if field.item.trim().is_empty() {
            return Err(Error::InvalidArgument(format!(
                "request field {index} has no 'item' (its visible prompt); a blank prompt \
                 renders blank with no error anywhere"
            )));
        }
    }
    Ok(())
}

/// Every encoding a 32-byte seed could plausibly be rendered in, for the create-request
/// boundary assertion.
///
/// Three rather than one because the point is to catch a seed that reached the body through a
/// route nobody anticipated, and whoever hand-rolled that route reached for whichever encoder
/// was nearest. Both base64 spellings are UNPADDED deliberately: for 32 bytes the padded
/// standard form is this one plus a single `=`, so a `contains` on the shorter string catches
/// the padded rendering too — four spellings covered by three needles.
fn seed_renderings(seed: &[u8; 32]) -> [String; 3] {
    [
        URL_SAFE_NO_PAD.encode(seed),
        STANDARD_NO_PAD.encode(seed),
        seed.iter().map(|b| format!("{b:02x}")).collect(),
    ]
}

/// Whether another page exists, for the two lists that page identically.
///
/// One function rather than two copies: shares and requests answer this the same way, and a
/// divergence between them would show up as one list quietly truncating and not the other.
/// Submissions are deliberately not among them: that endpoint is not paginated at all, so
/// [`SubmissionPage`] carries no paging figures for this to read.
fn page_has_more(
    page: u32,
    limit: u32,
    total: Option<u32>,
    total_pages: Option<u32>,
    rows: usize,
) -> bool {
    if let Some(total_pages) = total_pages {
        return page < total_pages;
    }
    if let Some(total) = total {
        return u64::from(page) * u64::from(limit) < u64::from(total);
    }
    // Nothing to go on but the page itself: a full page probably has a successor, and a
    // short one ends the walk.
    rows > 0 && rows as u32 >= limit
}

fn parse_success(response: ureq::Response) -> Result<Value> {
    let text = response
        .into_string()
        .map_err(|e| Error::Transport(format!("reading the response: {e}")))?;
    if text.is_empty() {
        return Ok(Value::Object(Map::new()));
    }
    // Swallowing the parse failure turned a successful create into an empty object, so the
    // caller got Error::Internal from the missing short_code and lost the content key for a
    // share that exists. Say what actually arrived instead.
    serde_json::from_str(&text).map_err(|e| {
        Error::InternalOwned(format!(
            "the API returned a success whose body is not JSON ({e}): {}",
            text.chars().take(200).collect::<String>()
        ))
    })
}

fn error_for(status: u16, response: ureq::Response) -> Error {
    let request_id = response
        .header("x-request-id")
        .or_else(|| response.header("x-amzn-requestid"))
        .map(str::to_string);
    let retry_after = response
        .header("retry-after")
        .and_then(|v| v.parse::<u64>().ok());

    let text = response.into_string().unwrap_or_default();
    let parsed: Value = serde_json::from_str(&text).unwrap_or(Value::Null);

    let message = parsed
        .get("message")
        .and_then(Value::as_str)
        .map(str::to_string)
        .unwrap_or_else(|| {
            if text.is_empty() {
                format!("HTTP {status}")
            } else {
                text.chars().take(200).collect()
            }
        });
    let code = parsed.get("error_code").and_then(Value::as_i64);
    let details = ApiDetails {
        message,
        status,
        code,
        request_id,
    };

    match status {
        401 => Error::Authentication(details),
        // A spent allowance is a 403 like a missing scope, but the remedies are opposite: one
        // needs a plan change, the other a different key. The numeric code separates them.
        403 if code == Some(QUOTA_EXCEEDED_CODE) => Error::QuotaExceeded(details),
        403 => Error::Permission(details),
        404 => Error::NotFound(details),
        409 if code == Some(IDEMPOTENCY_CONFLICT_CODE) => Error::IdempotencyConflict(details),
        429 => Error::RateLimited {
            details,
            retry_after,
        },
        503 => Error::ServiceUnavailable(details),
        _ => Error::Api(details),
    }
}

fn random_token() -> String {
    let mut raw = [0u8; 16];
    OsRng.fill_bytes(&mut raw);
    raw.iter().map(|b| format!("{b:02x}")).collect()
}
